server:
    port: 8011
spring:
    application:
        name: spirng-boot-rabbitmq
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/test
        username: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                hbm2ddl:
                    auto: update
        show-sql: true
    rabbitmq:
        host: 127.0.0.1
        listener:
            direct:
                acknowledge-mode: manual
            simple:
                acknowledge-mode: manual
        password: guest
        port: 5672
        publisher-confirms: true
        publisher-returns: true
        username: guest
    thymeleaf:
        cache: false
